if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "19")
	if(NOT DEFINED ENV{APPVEYOR})
		message("--> VS2015 KIT used")
		include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2015-64_v01.cmake") # vs2015 (actual kit)
	else()
		message("--> VS2015 KIT used (AppVeyor packages)")
		include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2015-64_v01-AppVeyor.cmake") # vs2015 (actual kit)
	endif()
elseif (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "18")
#	message("--> NO VS2013 KIT !") # vs2013 (no kit...)
elseif (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "17")
	message("--> VS2012 KIT used")
	include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2012-64_v07.cmake") # vs2012 (old kit, deprecated)
elseif (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "16")
	message("--> VS2010 KIT used")
	include("${CMAKE_SOURCE_DIR}/cmake/msvc/kit_vs2010-64_v01.cmake") # vs2010 (old kit, deprecated)
endif()