# - Try to findOPENMESH
# Once done this will define
#  
# OPENMESH_FOUND			- system has OPENMESH
# OPENMESH_INCLUDE_DIR		- the OPENMESH include directory
# OPENMESH_LIBRARY			- Link these to use OPENMESH
# OPENMESH_LIBRARY_DIR		- Library DIR of OPENMESH
#   

IF (OPENMESH_INCLUDE_DIR)
  # Already in cache, be silent
  SET(OPENMESH_FIND_QUIETLY TRUE)
ENDIF (OPENMESH_INCLUDE_DIR)

FIND_PATH(OPENMESH_INCLUDE_DIR OpenMesh/Core/Mesh/PolyMeshT.hh
	  PATHS /usr/local/include 
                /usr/include 
                /opt/local/include
				/opt/include
                $ENV{OPENMESH_DIR}/include 
                )

IF (OPENMESH_INCLUDE_DIR )
   SET(OPENMESH_FOUND TRUE)
IF (WIN32)
   SET(OPENMESH_LIBRARY_DIR "${OPENMESH_INCLUDE_DIR}/../lib")
ELSE (WIN32)
   SET(OPENMESH_LIBRARY_DIR "${OPENMESH_INCLUDE_DIR}/../lib/OpenMesh")
ENDIF (WIN32)
   # SET(OPENMESH_LIBRARY "OpenMeshCore;OpenMeshTools")
   
   FIND_LIBRARY(OPENMESH_CORE_LIBRARY_RELEASE NAMES OpenMeshCore PATHS ${OPENMESH_LIBRARY_DIR})
   FIND_LIBRARY(OPENMESH_TOOLS_LIBRARY_RELEASE NAMES OpenMeshTools PATHS ${OPENMESH_LIBRARY_DIR})
   SET(OPENMESH_LIBRARY_RELEASE
        ${OPENMESH_CORE_LIBRARY_RELEASE}
        ${OPENMESH_TOOLS_LIBRARY_RELEASE})
        
   FIND_LIBRARY(OPENMESH_CORE_LIBRARY_DEBUG NAMES OpenMeshCored PATHS ${OPENMESH_LIBRARY_DIR})
   FIND_LIBRARY(OPENMESH_TOOLS_LIBRARY_DEBUG NAMES OpenMeshToolsd PATHS ${OPENMESH_LIBRARY_DIR})
   SET(OPENMESH_LIBRARY_DEBUG
        ${OPENMESH_CORE_LIBRARY_DEBUG}
        ${OPENMESH_TOOLS_LIBRARY_DEBUG})
        
   set(OPENMESH_LIBRARY optimized ${OPENMESH_LIBRARY_RELEASE} debug ${OPENMESH_LIBRARY_DEBUG})
ELSE (OPENMESH_INCLUDE_DIR)
   SET(OPENMESH_FOUND FALSE )
ENDIF (OPENMESH_INCLUDE_DIR )

